### ISSUE TITLE
Getting Errors during setup

### ISSUE THREAD

**Issue by pktalatham** [kiwiz/411-docker#1]
Hi there,

I'm using 411 on top of an OSSEC-ELK stack and I keep getting these errors:

"Error getting active count data"
"Error executing query"
Do you know what could be causing these issues?

**Comment by kiwiz** [comment]
What version of ES are you using? Make sure to use the 5.x branch if you're using the newest version of ES.

**Comment by pktalatham** [comment]
That was the issue. Thanks!

**Comment by pktalatham** [comment]
I am now getting these errors after building with the correct version of 411:

Mon, 19 Jun 2017 15:37:55 GMT	SQLSTATE[HY000]: General error: 8 attempt to write a readonly database
Mon, 19 Jun 2017 15:34:05 GMT	Error: Uncaught TypeError: Cannot use 'in' operator to search for 'success' in <br /> <b>Fatal error</b>: Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51 Stack trace: #0 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(72): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool-&gt;nextConnection() #1 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(90): Elasticsearch\Transport-&gt;getConnection() #2 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(240): Elasticsearch\Transport-&gt;performRequest('HEAD', '/_template/411_...', Array, NULL, Array) #3 /var/www/411/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection-&gt;Elasticsearch\Connections\{closure}(Array) #4 /var/www/411/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise-&gt;then(Object(Closure), NULL, NULL) #5 /var/ in <b>/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php</b> on line <b>51</b><br />
Mon, 19 Jun 2017 15:34:02 GMT	No alive nodes found in your cluster

![image](https://user-images.githubusercontent.com/5676431/27293351-c20115ae-54db-11e7-98a0-6512982ae95e.png)

Any ideas on what is causing this issue?

**Comment by kiwiz** [comment]
Ah, the docker image I published has a perms issue. I've pushed a fix to GH and I can trigger a dockerhub rebuild tonight.

**Comment by pktalatham** [comment]
That resolved the create user issue!
But whenever I navigate to the home page or alerts page I'm still getting those two other errors. It seems that 411 can not connect to elasticsearch. Any suggestions there?

![image](https://user-images.githubusercontent.com/5676431/27340768-f5dbbada-55a0-11e7-988a-79da03353097.png)

**Comment by kiwiz** [comment]
You'll need to update the config file within the volume. The config file bundled with this docker container assumes elasticsearch is located at the host `es`.

See https://docs.docker.com/engine/tutorials/dockervolumes/#locate-a-volume for deetz.

**Comment by pktalatham** [comment]
That config within /data is accurate and the same as the config in /var/www/411 and we have the elasticsearch config options pointed to  'hosts' => ['http://elasticsearch:9200'], We can curl that and get a response but 411 is still having that no alive nodes found issue.

**Comment by kiwiz** [comment]
Possibly a networking issue? Afaik, by default docker bridges vms into your network so that shouldn't be a problem. Try curling ES from within a docker container:

`docker run -it -p 8080:80 kaiz/411 'curl http://elasticsearch:9200'` or something like that.

**Comment by pktalatham** [comment]
The curl works. so It shouldn't be a networking issue.

**Comment by kiwiz** [comment]
Try constructing an ES object from within the container:

```<?php

require('/var/www/411/vendor/autoload.php');

$cb = \Elasticsearch\ClientBuilder::create();
$cb->setHosts(['http://elasticsearch:9200']);
$es = $cb->build();
$es->search();
```

**Comment by pktalatham** [comment]
Ran that but I was not able to decipher how that would solve the problem. Restarted apache and I'm still getting those errors.

**Comment by kiwiz** [comment]
Whoops, I left out a line. Can you run the update script above? The script tries to connect to ES from PHP, so if it throws an exception that might shed more light.

**Comment by pktalatham** [comment]
Ran it with no errors or exceptions.

**Comment by kiwiz** [comment]
Did you copy the entire script? I'd expect it to die on `$cb->setHosts` if `$cb` was null.

**Comment by pktalatham** [comment]
Yup copy pasta'd and no errors or exceptions this time.

**Comment by kiwiz** [comment]
Just bumped the versions. Can you give newest release a try?

**Comment by pktalatham** [comment]
I see the change in the git repo, but the newest tag found in dockerhub was last updated 2 days ago.

I took the changes you made in the 411-docker repo and added that to ours and built the image. I'm still seeing the same error though. Are you able to replicate this error? I'm seeing it in our test env as well as locally.

**Comment by kiwiz** [comment]
I haven't been able to reproduce this issue (on master, at least). Things I've tried:

- Spinning up a test instance using the `docker-compose.yml` file. 411 is able to communicate with the es container. 
- Setting up a standalone 411 container. I modified the `config.php` file to point at a remote es cluster and that works too.

**Comment by spaceB0x** [comment]
Hey kiwiz. Thank you for looking into this for us. I was on the team that pktalatham was on implementing this. We are actually on the es-5x branch attempting this. And running just the base docker compose file fails as well.  I think it might be specific to that branch, but not sure.

**Comment by kiwiz** [comment]
Hey, I just tried building es-5.x from a completely clean slate (`docker-compose build --force-rm --no-cache --pull`) and it's able to connect to the docker elasticsearch container. Can you try the same just in case?

**Comment by spaceB0x** [comment]
Thank you this actually built successfully locally. I will see if I can integrate this again into our current stack. Thank you for your help.

**Comment by spaceB0x** [comment]
It appears that the problem exists with the version of ES. We were attempting with 5.3.0, while the given repository is on 5.4.2. I tried building the image pointing to ES 5.3.0 and that is when it crashed. Must be a version thing. I may investigate upgrading to 5.4.2

**Comment by kiwiz** [comment]
Closing this out as it seems to be resolved. Feel free to reopen if you've addn questions!
